### ISSUE TITLE
Dredd error with self-signed certificates

### ISSUE THREAD

**Issue by LYDE1234** [microsoft/rest-api-fuzz-testing#195]
We use a self-signed certificate during development and get this when running Dredd:

Error: 
Error: unable to verify the first certificate
Stacktrace: 
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:932:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706:12)

is there a way to work around this either via RAFT or Dredd itself?

**Comment by stishkin** [comment]
Seems like Dredd has open issues related to this. Once those are addressed, raft will be able to use that. 



https://github.com/apiaryio/dredd/issues/913
https://github.com/apiaryio/dredd/issues/323


There might be an option to add the certificate to the certificate store on the container (we did that with RESTler). I'll investigate if same solution would work for Dredd

**Comment by stishkin** [comment]
@LYDE1234  - does disabling certificate validation altogether would work for you ?
