### ISSUE TITLE
Schemathesis ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by Sticcia** [microsoft/rest-api-fuzz-testing#197]
Execution of Schemathesis (in local deployment) fails to import package 'six' in Docker container.
Log shows following:
```
Installing collected packages: six, oauthlib, requests-oauthlib, isodate, uamqp, msrest, azure-core, azure-common, azure-servicebus, applicationinsights
  Attempting uninstall: six
    Found existing installation: six 1.16.0
    Uninstalling six-1.16.0:
      Successfully uninstalled six-1.16.0
Successfully installed applicationinsights-0.11.10 azure-common-1.1.27 azure-core-1.13.0 azure-servicebus-7.0.1 isodate-0.6.0 msrest-0.6.21 oauthlib-3.1.0 requests-oauthlib-1.3.0 six-1.15.0 uamqp-1.4.0
```
Although six-1.15.0 is "Successfully installed", the run.py script fails with:
```
Traceback (most recent call last):
  File "/usr/local/bin/schemathesis", line 5, in <module>
    from schemathesis.cli import schemathesis
  File "/usr/local/lib/python3.9/site-packages/schemathesis/__init__.py", line 1, in <module>
    from . import fixups, hooks, runner, serializers, targets
  File "/usr/local/lib/python3.9/site-packages/schemathesis/runner/__init__.py", line 7, in <module>
    from ..checks import DEFAULT_CHECKS
  File "/usr/local/lib/python3.9/site-packages/schemathesis/checks.py", line 3, in <module>
    from .exceptions import get_status_code_error
  File "/usr/local/lib/python3.9/site-packages/schemathesis/exceptions.py", line 8, in <module>
    from jsonschema import ValidationError
  File "/usr/local/lib/python3.9/site-packages/jsonschema/__init__.py", line 22, in <module>
    from jsonschema.validators import (
  File "/usr/local/lib/python3.9/site-packages/jsonschema/validators.py", line 11, in <module>
    from six import add_metaclass
ModuleNotFoundError: No module named 'six'
```

Installation of one of the packages is causing the issue.
A possible work-around is adding: `--ignore-installed six` as an argument when installing packages.
In \cli\raft-tools\tools\Schemathesis\run.py, line 14:
``` Python
subprocess.check_call([sys.executable, "-m", "pip", "install", "--no-cache-dir", "--root", "/tmp", "-r", os.path.join(raft_libs_dir, "requirements.txt"), "--ignore-installed", "six"])
```

**Comment by stishkin** [comment]
Thank you,

I have a PR where this issue is resolved by removing the dependency altogether. And using a proxy container for handling all of those calls.
