### ISSUE TITLE
[v4] Token authentication error

### ISSUE THREAD

**Issue by Sticcia** [microsoft/rest-api-fuzz-testing#203]
Running in a local deployment on the new version with agent-utilities.
I encounter the following error with multiple tools.
My configuration template:
```JSON
{
  "testTasks" : {
    "targetConfiguration": {
      "apiSpecifications": [
        "<specification-url>"
      ],
      "endpoint": "<endpoint-url>"
    },
    "tasks": [
      {
        "toolName": "ZAP",
        "outputFolder": "zap",
        "keyVaultSecrets": [ "TOKEN" ],
        "authenticationMethod": {
            "Token": "Token"
        }
      }
    ]
  }
}
```
Where Token is file in \cli\local\secrets\ containing:
`Basic <base64-auth-token>=`

Execution fails in container before running any tasks.

`zap2docker` container log:
```
Traceback (most recent call last):
File "run.py", line 18, in <module>
token = raft.auth_token()
File "/raft-tools/tools/ZAP/../../libs/python3/raft.py", line 76, in auth_token
raise Exception(response.text)
Exception: {"error":"Traceback (most recent call last): File \"/raft-tools/agent-utilities/auth/python3/token/token.py\", line 13, in <module> token = token_from_env_variable(sys.argv[1]) File \"/raft-tools/agent-utilities/auth/python3/token/token.py\", line 10, in token_from_env_variable raise Exception(f\"Token environment variable is not set {env_variable_name}\")Exception: Token environment variable is not set RAFT_TOKEN"}
```

Replacing toolName in config with `Dredd` will give similar error.
`dredd` container log:
```
Authentication Method: Token
Error: Request to http://localhost:8085/auth/Token/Token failed with status code 400
at ClientRequest.<anonymous> (/raft-tools/libs/node-js/raft.js:179:34)
at Object.onceWrapper (events.js:483:26)
at ClientRequest.emit (events.js:376:20)
at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:647:27)
at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
at Socket.socketOnData (_http_client.js:515:22)
at Socket.emit (events.js:376:20)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:284:9)
at Socket.Readable.push (internal/streams/readable.js:223:10)
(node:8) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
at JSON.parse (<anonymous>)
at IncomingMessage.<anonymous> (/raft-tools/libs/node-js/raft.js:81:57)
at IncomingMessage.emit (events.js:388:22)
at endReadableNT (internal/streams/readable.js:1336:12)
at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Inspecting the containers with Docker Hub shows the environment variable `RAFT_TOKEN` is being set correctly: `Basic <base64-auth-token>=`.

Ignoring the Token with the following "ugly" work-around seems to solve.
Replace the last 3 lines in `token.py` with:
```Python
if __name__ == "__main__":
    print("Basic <base64-auth-token>=")
```
I'm guessing the issue occurs when reading the environment variable:
```Python
auth_params = os.environ.get(env_variable_name)
```

**Comment by stishkin** [comment]
@Sticcia - so when agent utilities are used, ZAP docker container. It should request it using http://localhost, just like in Dredd case.

Do you have the following script in your CLI agent utilities folder ? 

`RAFT-CLI\raft-tools\agent-utilities\auth\token.sh`

**Comment by Sticcia** [comment]
@stishkin - yes, `token.sh` is as follows:
```bash
python3 /raft-tools/agent-utilities/auth/python3/token/token.py $1
```

Error is also thrown with Schemathesis and RESTler (log is the same as ZAP).

**Comment by Sticcia** [comment]
@stishkin - Closing the issue with a bit of shame.

I swapped line 5 of `token.py`:
```Python
auth_params = os.environ.get(env_variable_name)
```
with:
```Python
auth_params = os.environ[env_variable_name]
```
hoping for a clearer exception to be thrown in the log.

It did work, as I manage to get the following:
```
Exception: {"error":"Traceback (most recent call last): File \"/raft-tools/agent-utilities/auth/python3/token/token.py\", line 13, in <module> token = token_from_env_variable(sys.argv[1]) File \"/raft-tools/agent-utilities/auth/python3/token/token.py\", line 5, in token_from_env_variable auth_params = os.environ[env_variable_name] File \"/usr/lib/python3.7/os.py\", line 678, in __getitem__ raise KeyError(key) from NoneKeyError: 'RAFT_TOKEN\\r'"}
```
`NoneKeyError: 'RAFT_TOKEN\\r'`

Don't ask me how, don't ask me when, but apparently a new line was added to `token.sh` and broke the script.
My guess is Git changing everything to Windows-style when pulling was the cause.

Thank you for the time wasted. :P

**Comment by stishkin** [comment]
I see, this is still a bug on our part. Ok, I think I know what we can improve
